#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: md5all FILE1 FILE2 ..."
    echo ""
    echo "Generates FILE.md5 with md5 checksum for each given FILE."
    exit 1
fi

CUR_DIR=`pwd`

for F in $*; do
    BASE_F=`basename $F`
    DIR_F=`dirname $F`
    cd $DIR_F
    md5sum $BASE_F > $BASE_F.md5
    cd $CUR_DIR
done
