#!/bin/bash

#
# Tangle all files given in argument with org-mode
#

if [ "$EMACS_HOME" == "" ]; then
    echo "No EMACS_HOME variable, exiting ..."
    exit 1
fi


DIR=`pwd`
FILES=""

# wrap each argument in the code required to call tangle on it
for i in $@; do
    FILES="$FILES \"$i\""
done

$EMACS_HOME/bin/emacs -Q --batch \
    --eval "(progn
       (add-to-list 'load-path (expand-file-name \"~/src/org/lisp/\"))
       (add-to-list 'load-path (expand-file-name \"~/src/org/contrib/lisp/\" t))
       (require 'org)(require 'ob)(require 'ob-tangle)
       (mapc (lambda (file)
       (find-file (expand-file-name file \"$DIR\"))
       (org-babel-tangle)
       (kill-buffer)) '($FILES)))" 2>&1 | grep Tangled
